export const SET_EMPLOYEE_ID = 'SET_EMPLOYEE_ID';
export const SET_MANAGER_ID = 'SET_MANAGER_ID';
export const UPDATE_EMPLOYEE_INFO = 'UPDATE_EMPLOYEE_INFO';
export const UPDATE_MANAGER_INFO = 'UPDATE_MANAGER_INFO';
export const RESET_ACCOUNT_INFO = 'RESET_ACCOUNT_INFO';